const EVENTS = {
  connection: "connection",
  CLIENT: {
    SEND_MESSAGE: "SEND_MESSAGE",
    VOTE_TEAM: "VOTE_TEAM",
    CURRENT_VOTES: "CURRENT_VOTES",
    CHECK_AUTH: "CHECK_AUTH",
    TOTAL_USERS: "TOTAL_USERS",
    WHOAMI: "WHOAMI",
  },
  SERVER: {
    SEND_MESSAGES: "SEND_MESSAGES",
    CURRENT_VOTES: "CURRENT_VOTES",
    AUTH_RESPONSE: "AUTH_RESPONSE",
    WHOAMI_RESP: "WHOAMI_RESP",
    TOTAL_USERS_RESP: "TOTAL_USERS_RESP",
  },
};

export default EVENTS;
